ci: add github action workflow to build & push docker image to quay.io
cilium/team-manager pull request #21
Opened 2023-07-06 07:36 UTC by mhofstetter

This PR adds the GitHub Actions workflow `Docker Image` which builds & pushes the docker image to quay.io.

2023-07-07 15:49 UTC, aanm requested changes

2023-07-07 15:49 UTC, aanm commented on .github/workflows/docker-dev.yaml
> +            quay.io/${{ github.repository_owner }}/team-manager-dev:${{ steps.tag.outputs.tag }}
to be consistent with the remaining workflows, this should be `team-manager-ci` instead

2023-07-07 15:49 UTC, aanm commented on .github/workflows/docker-release.yaml
> +    name: Build & Push
needs a `environment: release`, which is where we will store the credentials

2023-07-07 15:49 UTC, aanm commented on .github/workflows/docker-dev.yaml
> +          username: ${{ secrets.QUAY_DEV_USERNAME }}
`QUAY_DEV_USERNAME` -> `QUAY_CI_USERNAME`

2023-07-07 15:49 UTC, aanm commented on .github/workflows/docker-dev.yaml
> +          password: ${{ secrets.QUAY_DEV_TOKEN }}
`QUAY_DEV_TOKEN` -> `QUAY_CI_TOKEN`

2023-07-07 15:49 UTC, aanm commented on .github/workflows/docker-release.yaml
> +          username: ${{ secrets.QUAY_USERNAME }}
QUAY_RELEASE_USERNAME

2023-07-07 15:49 UTC, aanm commented on .github/workflows/docker-release.yaml
> +          password: ${{ secrets.QUAY_TOKEN }}
QUAY_RELEASE_TOKEN

2023-07-10 04:49 UTC, mhofstetter commented
@aanm Thanks for your review and creation of the secrets!

2023-07-10 18:35 UTC, aanm approved these changes

2023-07-10 18:35 UTC, merged