Feature: Team mentor status
cilium/team-manager pull request #28
Opened 2024-12-06 02:25 UTC by jspaleta

This pull request provides a working implementation of a team mentor status, meant to simplify the encoding of knowledgable team members who are no longer active in the automatic team review notification automation.

### Highlights
1. A top level cli command is added `set-team-mentors` which allows you to populate the team mentor list. This follows the pattern set by the `set-team` command which populates the member list. It can also be used to remove the list of mentors by leaving the argument blank. A future enhancement could be further extended to let you add/remove individuals from the team member and mentor list, but I wanted to start with the set command as a first cut.

2. This is strictly additive change to the excluded github userIDs sent to the github API when configuration review notification for a team. It does not interfere with the existing org wide `excludeCodeReviewAssignmentFromAllTeams` config or the team specific `codeReviewAssignment.excludedMembers`.  The intent is that these other mechanisms can be deprecated after configs are converted to using the team mentor concept, to ensure a smooth transition.  Note: the github API doesn't let you query back which userIDs are currently excluded from review, so this is really just a matter of configuration state as a source of truth. 

3. Enhanced user status reporting by the `status` to indicate where in the team management config users are excluded.

2024-12-06 02:29 UTC, jspaleta commented
I should note. I've tested locally using the MillionDollarIdea github org.

2024-12-06 20:36 UTC, jspaleta commented
This work is related to cilium/community/#178

2024-12-11 18:47 UTC, jspaleta commented
I've extended this PR to include an optional team override file in the configuration.

The team override file is a subset of the full Team configuration meant to be held in the public view while the full configuration is kept private.

The TeamOverrideConfig  includes only team names, and github usernames for team members and mentors.

The team override file is a strict override of team member and mentor lists only on a per team basis, for teams intended to be managed in the public view. Once the CI build is complete I'll update the MillionDollarIdea repo with an example of the override in use.

2024-12-11 20:47 UTC, jspaleta commented
I now have the MillionDollarIdeas Org updated to make use of the proposed team override from the latest CI build of this PR.

Public team information located at:
https://github.com/MillionDollarIdeas/team-assignments

Full Team management configuration located in private repo:
https://github.com/MillionDollarIdeas/team-management

repo-dispatch event is used to trigger private team-management workflow when public team membership info is updated.

2025-01-17 18:40 UTC, joestringer requested changes
I made a few small suggestions. The sorting of the members vs mentors should be fixed before merge. We can discuss whether to fix up the error handling for ineffective overrides or patch that up on top.

If this was in cilium/cilium I'd push for a bit more git hygiene around splitting the commits into each feature (overrides, mentors) and avoiding extra commits to sync with the main branch, but for this repo I think it's less critical since we aren't likely to end up bisecting the git tree to find some bug. I'll probably end up squashing all the commits together.

2025-01-17 18:40 UTC, joestringer commented on README.md
> +        # Optional list of team mentors who will be excluded from team review notifications
There's another GitHub feature for "team review notifications" that will not be changed by this configuration. The intent here is specifically about review assignment.

```suggestion
        # Optional list of team mentors who will not be auto-assigned PRs for review
```

2025-01-17 18:40 UTC, joestringer commented on pkg/config/sort.go
> +		sort.Strings(team.Members)
Two things: Why not sort inline? Also the slice being sorted here is `team.Members` not `team.Mentors`.

```suggestion
		sort.Strings(team.Mentors)
```

2025-01-17 18:40 UTC, joestringer commented on pkg/config/config.go
> +			fmt.Printf("Override Warning: team %s missing from config\n", teamName)
It makes me slightly nervous to see errors just being printed to the commandline and not creating an actual Go error to send up the stack and trigger an actual error in the execution. I suspect this may just be following existing style in this codebase but this means that as a user of the tool, I need to not only run the tool and check that the exit code was successful, but actually scan all the output of the command to understand the operations and whether the changes were in fact successfully applied.

Logging like this is much better than completely ignoring the error conditions, just wondering how severe this error condition is for instance and what the user should end up doing in response to this.

Let's say we take a step back and we end up maybe messing up the aggregation script or someone creates a new team override but something is misspelled, I guess all the tooling will report successful but then in reality the invalid overrides are being completely ignored and the only trace is one line like this in a GitHub workflow somewhere? Would it be better at this stage to return up an error and reject the user input because the overrides are ineffective?

2025-01-17 18:46 UTC, jspaleta commented on pkg/config/config.go
> +			fmt.Printf("Override Warning: team %s missing from config\n", teamName)
I think I was following existing style. But I'll double check that.
I'm happy to turn this into a failure condition.
Being as conservative as possible makes sense.

2025-01-17 18:54 UTC, jspaleta commented on pkg/config/sort.go
> +		sort.Strings(team.Members)
i definitely need to sort team members as well as members.

The code isn't just sorting its de-duping. I'm following the pattern established by the existing sort logic for team members.

2025-01-17 18:55 UTC, jspaleta commented
If you prefer I can squash this down to a single commit or break out override support from mentor support.

2025-01-17 19:21 UTC, joestringer commented on pkg/config/sort.go
> +		sort.Strings(team.Members)
Oh yeah de-duping makes sense.

2025-01-17 22:28 UTC, joestringer approved these changes
LGTM. I see @aanm wanted to take a look too so I'll defer to him for further review / merge.

2025-01-22 13:02 UTC, aanm approved these changes
Thank you!

2025-01-22 13:02 UTC, merged