pkg/config: Support slackID field
cilium/team-manager pull request #8
Opened 2022-03-29 08:50 UTC by pchaigno

This new field will be used to ping users on Slack. Team manager only needs to know about it to allow it in the configuration file; it's not used by Team manager itself.

2022-03-30 21:23 UTC, aanm requested changes
* How can we retrieve the slackId?
* I assume the slackId is associated to a workspace, shouldn't we define the workspace name / ID somewhere as well?

2022-04-07 18:21 UTC, pchaigno commented
> How can we retrieve the slackId? 

I've retrieved [them](https://github.com/isovalent/team-management/pull/277/files) [manually](https://www.workast.com/help/articles/61000165203/). If this ends up being useful, I'll likely add validation by querying the Slack API or sending a request to https://isovalent.slack.com/team/[USER_ID]. 

> I assume the slackId is associated to a workspace, shouldn't we define the workspace name / ID somewhere as well?

Good point! I've added a `slackWorkspace` field with the workspace's domain name.

2022-04-09 01:34 UTC, aanm requested changes
My point with the previous comment was that we should have a comment somewhere explaining how people can retrieve slack Id and slack workspace ids.

2022-05-09 09:42 UTC, pchaigno commented
> My point with the previous comment was that we should have a comment somewhere explaining how people can retrieve slack Id and slack workspace ids.

The Slack workspace ID is just the URL. The Slack user ID can be found in each person's profile, under "More". That's how I retrieved them.
I've added comments to clarify that.

2022-05-09 21:27 UTC, aanm approved these changes

2022-05-09 21:27 UTC, merged